/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package datavalidationsystemassignment;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author Nthabiseng
 */
public class Data extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Data
     */
    public Data() {
        initComponents();
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtsurname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtmale = new javax.swing.JRadioButton();
        txtfemale = new javax.swing.JRadioButton();
        lage = new javax.swing.JLabel();
        nameResult = new javax.swing.JLabel();
        surnameResult = new javax.swing.JLabel();
        idResult = new javax.swing.JLabel();
        contactResult = new javax.swing.JLabel();
        emailResult = new javax.swing.JLabel();
        maleResult = new javax.swing.JLabel();
        femaleResult = new javax.swing.JLabel();
        ageResult = new javax.swing.JLabel();
        idResult1 = new javax.swing.JLabel();
        contactResult1 = new javax.swing.JLabel();
        result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 255));
        jPanel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("D");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("A");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 153));
        jLabel3.setText("T");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("A");

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        helpButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        helpButton.setText("HELP");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(helpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(84, 84, 84)
                .addComponent(jButton1)
                .addGap(34, 34, 34)
                .addComponent(jButton2)
                .addGap(32, 32, 32)
                .addComponent(helpButton)
                .addGap(36, 36, 36)
                .addComponent(exitButton)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("NAME:");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnameKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("SURNAME:");

        txtsurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsurnameActionPerformed(evt);
            }
        });
        txtsurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsurnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsurnameKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("ID:");

        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("CONTACT NO:");

        txtcon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtconKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("GENDER:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("AGE:");

        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtageKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtageKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("EMAIL:");

        txtmale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtmale.setText("MALE");
        txtmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaleActionPerformed(evt);
            }
        });
        txtmale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmaleKeyTyped(evt);
            }
        });

        txtfemale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtfemale.setText("FEMALE");
        txtfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfemaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtname)
                                    .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtfemale)
                                            .addComponent(txtmale)
                                            .addComponent(result)))
                                    .addComponent(nameResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(idResult1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(idResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(maleResult, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(femaleResult, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsurname, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(surnameResult, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                        .addComponent(txtage)
                                        .addComponent(txtcon))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lage)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ageResult))
                                            .addComponent(emailResult)
                                            .addComponent(contactResult, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(contactResult1)
                        .addGap(70, 70, 70))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtsurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameResult)
                    .addComponent(surnameResult))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idResult1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idResult)
                            .addComponent(contactResult))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contactResult1)))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lage)
                            .addComponent(maleResult)
                            .addComponent(ageResult)))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtfemale)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(femaleResult)
                    .addComponent(result))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailResult)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JLabel nameErrorLabel= new JLabel();
        nameErrorLabel.setForeground(Color.red);
        nameErrorLabel.setVisible(false);
        
        
        
        txtname.setText("");
        txtsurname.setText("");
        txtid.setText("");
        txtcon.setText("");
        txtage.setText("");
        txtemail.setText("");
        nameResult.setText("");
        surnameResult.setText("");
        idResult.setText("");
        contactResult.setText("");
        ageResult.setText("");
        emailResult.setText("");
        lage.setText("");
        
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:SS
            String age =txtage.getText();
            if(age.contains("18")||age.contains("19")||age.contains("20")||age.contains("21")||age.contains("22")
              ||age.contains("23")||age.contains("24")||age.contains("25")||age.contains("26")||age.contains("27")
              ||age.contains("28")||age.contains("29")||age.contains("30")||age.contains("31")||age.contains("32")
              ||age.contains("33")||age.contains("34")||age.contains("35")||age.contains("36")||age.contains("37")
              ||age.contains("38")||age.contains("39")||age.contains("40")||age.contains("41")||age.contains("42")
              ||age.contains("43")||age.contains("44")||age.contains("45")||age.contains("46")||age.contains("47")
              ||age.contains("48")||age.contains("49")||age.contains("50")||age.contains("51")||age.contains("52")
              ||age.contains("53")||age.contains("54")||age.contains("55")||age.contains("56")||age.contains("57")
              ||age.contains("58")||age.contains("59")||age.contains("60")||age.contains("61")||age.contains("62")
              ||age.contains("63")||age.contains("64")||age.contains("65")||age.contains("66")||age.contains("67")
              ||age.contains("68")||age.contains("69")||age.contains("70")||age.contains("71")||age.contains("72")
              ||age.contains("73")||age.contains("74")||age.contains("75")||age.contains("76")||age.contains("77")
              ||age.contains("78")||age.contains("79")||age.contains("80")||age.contains("81")||age.contains("82")
              ||age.contains("83")||age.contains("84")||age.contains("85")||age.contains("86")||age.contains("87")
              ||age.contains("88")||age.contains("89")||age.contains("90")||age.contains("91")||age.contains("92")
              ||age.contains("93")||age.contains("94")||age.contains("95")||age.contains("96")||age.contains("97")
              ||age.contains("98")||age.contains("99")||age.contains("100")||age.contains("101")||age.contains("102")
              ||age.contains("103")||age.contains("104")||age.contains("105")||age.contains("106")||age.contains("107")
              ||age.contains("108")||age.contains("109")||age.contains("110")||age.contains("111")||age.contains("112")
  ){
                lage.setText("Above 18");
                lage.setForeground(Color.BLUE);
            }
            else{
                if(age.contains("17")||age.contains("16")||age.contains("15")||age.contains("14")
                 ||age.contains("13")||age.contains("12")||age.contains("11")||age.contains("10")||age.contains("9")
                 ||age.contains("8")||age.contains("7")||age.contains("6")||age.contains("5")||age.contains("4")
                 ||age.contains("3")||age.contains("2")||age.contains("1")){
                    lage.setText("Below 18");
                    lage.setForeground(Color.red);
                }
                else{
                    lage.setText("Between 0 112");
                    lage.setForeground(Color.RED);
                }
            }
            
            String email =txtemail.getText();
            String name = txtname.getText();
            String surname = txtsurname.getText();
            String ID = txtid.getText();
            String contact = txtcon.getText();
            
            if(name.isBlank()){
                nameResult.setText("Field Empty");
                nameResult.setForeground(Color.red);
            }
            else{
                nameResult.setText("Validated");
                nameResult.setForeground(Color.BLUE);
            }
           
            
            if(surname.isBlank()){
                surnameResult.setText("Field Empty");
                surnameResult.setForeground(Color.red);
            }
            else{
                surnameResult.setText("Validated");
                surnameResult.setForeground(Color.BLUE);
            }
            
            if(ID.isBlank()){
                idResult.setText("Field Empty");
                idResult.setForeground(Color.red);
            }
            else{
                idResult.setText("Validated");
                idResult.setForeground(Color.BLUE);
            }
            
            if(contact.isBlank()){
                contactResult.setText("Field Empty");
                contactResult.setForeground(Color.red);
            }
            else{
                contactResult.setText("Validated");
                contactResult.setForeground(Color.BLUE);
            }
            if(contact.length()>10){
                contactResult.setText("Only 10 digits!");
                contactResult.setForeground(Color.red);
            }
            if(ID.length()>13){
                idResult.setText("Only 13 charecters");
                idResult.setForeground(Color.red);
            }
            if(age.isBlank()){
                ageResult.setText("Field Empty");
                ageResult.setForeground(Color.red);
                lage.setText("");
            }
           
            else{
                ageResult.setText("");
            }
            
            if(!txtmale.isSelected()&&!txtfemale.isSelected()){
                result.setText("Field Empty");
                result.setForeground(Color.red);
            }
            
            else if(txtmale.isSelected()){
                    result.setText("Male");
                    result.setForeground(Color.yellow);
                
            }
            
            else if(txtfemale.isSelected()){
                    result.setText("Female");
                    result.setForeground(Color.YELLOW);
            }
           
            
            if(email.isEmpty()){
                emailResult.setText("Field Empty");
                emailResult.setForeground(Color.RED);
            }
            else{
                emailResult.setText("");
            }
            if(!email.contains("@")||!email.contains(".com")){
                emailResult.setText("Incorrect Email");
                emailResult.setForeground(Color.red);
            }
            else{
                emailResult.setText("Validated");
                emailResult.setForeground(Color.BLUE);
            }
            
                   
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtidKeyTyped

    private void txtnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyTyped
        // TODO add your handling code here:
        if(!(Character.isAlphabetic(evt.getKeyChar()) || Character.isWhitespace(evt.getKeyChar()))){
            evt.consume();
        }
    }//GEN-LAST:event_txtnameKeyTyped

    private void txtsurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsurnameActionPerformed

    private void txtsurnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsurnameKeyTyped
        // TODO add your handling code here:
        if(!(Character.isAlphabetic(evt.getKeyChar()) || Character.isWhitespace(evt.getKeyChar()))){
            evt.consume();
        }
        
    }//GEN-LAST:event_txtsurnameKeyTyped

    private void txtconKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconKeyTyped
        // TODO add your handling code here:
         if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtconKeyTyped

    private void txtageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtageKeyTyped

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        
            exitButton.setBackground(new java.awt.Color(255, 255, 255));
            exitButton.setForeground(new java.awt.Color(0, 0, 0));
            exitButton.setText("EXIT");
            exitButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    exitButtonActionPerformed(evt);
                }
            });
            System.exit(0);
               

    }//GEN-LAST:event_exitButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
        helpButton.setBackground(new java.awt.Color(255, 255, 255));
        helpButton.setForeground(new java.awt.Color(0, 0, 0));
        helpButton.setText("HELP");
        helpButton.addActionListener(new  java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        new How().setVisible(true);
        dispose();

    }//GEN-LAST:event_helpButtonActionPerformed

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        // TODO add your handling code here:
                    char c = evt.getKeyChar();
                    if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
                        txtname.setEditable(true);
                        nameResult.setForeground(Color.BLUE);
                        nameResult.setText("Valid");
                    }
                    else{
                        txtname.setEditable(false);
                        nameResult.setText("Letters Only");
                        nameResult.setForeground(Color.red);
                    }
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtsurnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsurnameKeyPressed
        // TODO add your handling code here:
                    char c = evt.getKeyChar();
                    if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
                        txtsurname.setEditable(true);
                        surnameResult.setForeground(Color.BLUE);
                        surnameResult.setText("Valid");
                    }
                    else{
                        txtsurname.setEditable(false);
                        surnameResult.setText("Letters Only");
                        surnameResult.setForeground(Color.red);
                    }
                
    }//GEN-LAST:event_txtsurnameKeyPressed

    private void txtmaleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmaleKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaleKeyTyped

    private void txtmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaleActionPerformed
        // TODO add your handling code here:
            if(txtmale.isSelected()){
                result.setText("Male");
                result.setForeground(Color.yellow);
            }
            else if(!txtmale.isSelected()&&txtfemale.isSelected()){
                result.setText("");
            }
    }//GEN-LAST:event_txtmaleActionPerformed

    private void txtfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfemaleActionPerformed
        // TODO add your handling code here:
        if(txtfemale.isSelected()){
                result.setText("Female");
                result.setForeground(Color.yellow);
            }
        
            else if(!txtfemale.isSelected()&&txtmale.isSelected()){
                result.setText("");
            }
    }//GEN-LAST:event_txtfemaleActionPerformed

    private void txtageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyPressed
        // TODO add your handling code here:
                char c = evt.getKeyChar();
                if(Character.isLetter(c)){
                    txtage.setEditable(false);
                    ageResult.setText("Numbers Only");
                    ageResult.setForeground(Color.red);
                }
                else{
                    ageResult.setForeground(Color.BLUE);
                    ageResult.setText("Valid");
                    txtage.setEditable(true);
                }
    }//GEN-LAST:event_txtageKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageResult;
    private javax.swing.JLabel contactResult;
    private javax.swing.JLabel contactResult1;
    private javax.swing.JLabel emailResult;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel femaleResult;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel idResult;
    private javax.swing.JLabel idResult1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lage;
    private javax.swing.JLabel maleResult;
    private javax.swing.JLabel nameResult;
    private javax.swing.JLabel result;
    private javax.swing.JLabel surnameResult;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcon;
    private javax.swing.JTextField txtemail;
    private javax.swing.JRadioButton txtfemale;
    private javax.swing.JTextField txtid;
    private javax.swing.JRadioButton txtmale;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsurname;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("OIP.jpg")));
    }
}
